In [1]:
import pandas as pd

In [14]:
food_1 = pd.read_csv("../data/FOOD-DATA-GROUP1.csv")
food_1 = food_1.drop(["Unnamed: 0", "Unnamed: 0.1", "Nutrition Density"], axis=1)
food_1.head()

,food,Caloric Value,Fat,Saturated Fats,Monounsaturated Fats,Polyunsaturated Fats,Carbohydrates,Sugars,Protein,Dietary Fiber,...,Vitamin K,Calcium,Copper,Iron,Magnesium,Manganese,Phosphorus,Potassium,Selenium,Zinc
0,cream cheese,51,5.0,2.9,1.3,0.200,0.8,0.500,0.9,0.0,...,0.100,0.008,14.100,0.082,0.027,1.300,0.091,15.5,19.100,0.039
1,neufchatel cheese,215,19.4,10.9,4.9,0.800,3.1,2.700,7.8,0.0,...,0.045,99.500,0.034,0.100,8.500,0.088,117.300,129.2,0.054,0.700
2,requeijao cremoso light catupiry,49,3.6,2.3,0.9,0.000,0.9,3.400,0.8,0.1,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.0,0.000,0.000
3,ricotta cheese,30,2.0,1.3,0.5,0.002,1.5,0.091,1.5,0.0,...,0.011,0.097,41.200,0.097,0.096,4.000,0.024,30.8,43.800,0.035
4,cream cheese low fat,30,2.3,1.4,0.6,0.042,1.2,0.900,1.2,0.0,...,0.019,22.200,0.072,0.008,1.200,0.098,22.800,37.1,0.034,0.053

In [15]:
food_2 = pd.read_csv("../data/FOOD-DATA-GROUP2.csv")
food_2 = food_2.drop(["Unnamed: 0", "Unnamed: 0.1", "Nutrition Density"], axis=1)
food_2.head()

,food,Caloric Value,Fat,Saturated Fats,Monounsaturated Fats,Polyunsaturated Fats,Carbohydrates,Sugars,Protein,Dietary Fiber,...,Vitamin K,Calcium,Copper,Iron,Magnesium,Manganese,Phosphorus,Potassium,Selenium,Zinc
0,eggnog,224,10.6,6.6,3.3,0.5,20.4,20.4,11.600,0.0,...,0.011,330.2,0.051,0.500,48.3,0.024,276.9,419.1,0.094,1.200
1,beer light,96,0.0,0.0,0.0,0.0,5.4,0.3,0.800,0.0,...,0.000,13.2,0.095,0.014,16.5,0.094,39.6,69.3,0.077,0.044
2,beer budweiser,12,0.0,0.0,0.0,0.0,0.9,0.0,0.100,0.0,...,0.000,1.2,0.095,0.000,2.1,0.038,3.8,9.7,0.000,0.000
3,weizenbier erdinger,220,18.0,13.0,1.0,0.0,0.0,0.0,0.000,0.0,...,0.000,0.0,0.000,0.000,0.0,0.000,0.0,0.0,0.000,0.000
4,beer light budweiser,9,0.0,0.0,0.0,0.0,0.4,0.0,0.066,0.0,...,0.000,0.9,0.088,0.000,2.1,0.007,3.2,7.7,0.000,0.000

In [16]:
food_3 = pd.read_csv("../data/FOOD-DATA-GROUP3.csv")
food_3 = food_3.drop(["Unnamed: 0", "Unnamed: 0.1", "Nutrition Density"], axis=1)
food_3.head()

,food,Caloric Value,Fat,Saturated Fats,Monounsaturated Fats,Polyunsaturated Fats,Carbohydrates,Sugars,Protein,Dietary Fiber,...,Vitamin K,Calcium,Copper,Iron,Magnesium,Manganese,Phosphorus,Potassium,Selenium,Zinc
0,nectarine,66,0.500,0.066,0.100,0.200,15.8,11.8,1.600,2.6,...,1.200,0.081,9.000,0.100,0.4,13.500,0.002,39.0,301.500,0.000
1,kiwifruit gold,51,0.200,0.008,0.099,0.051,12.8,10.0,0.800,1.1,...,0.074,13.800,0.100,0.200,9.7,0.072,20.300,255.2,0.003,0.077
2,prickly pear raw,8,0.072,0.000,0.000,0.000,1.9,0.2,0.001,1.0,...,0.018,34.200,0.051,0.021,13.1,0.100,2.100,24.7,0.023,0.073
3,pineapple,45,0.100,0.074,0.001,0.087,11.8,8.9,0.500,1.3,...,0.078,0.061,11.700,0.091,0.3,10.800,0.800,7.2,98.100,0.061
4,rowan,253,4.600,0.600,0.000,0.000,54.5,32.1,5.200,14.1,...,0.000,34.200,2.400,5.000,73.0,0.400,118.600,298.7,0.000,1.000

In [17]:
food_4 = pd.read_csv("../data/FOOD-DATA-GROUP4.csv")
food_4 = food_4.drop(["Unnamed: 0", "Unnamed: 0.1", "Nutrition Density"], axis=1)
food_4.head()

,food,Caloric Value,Fat,Saturated Fats,Monounsaturated Fats,Polyunsaturated Fats,Carbohydrates,Sugars,Protein,Dietary Fiber,...,Vitamin K,Calcium,Copper,Iron,Magnesium,Manganese,Phosphorus,Potassium,Selenium,Zinc
0,chocolate pudding fat free,105,0.3,0.0,0.00,0.000,23.6,17.8,2.2,0.3,...,0.098,44.100,0.035,1.900,17.0,0.040,61.0,235.0,0.052,0.300
1,tapioca pudding,143,4.3,1.1,2.80,0.088,23.9,16.4,2.1,0.0,...,0.010,78.100,0.026,0.100,6.6,0.096,66.0,101.2,0.000,0.200
2,tapioca pudding fat free,105,0.4,0.1,0.08,0.067,23.9,15.9,1.6,0.0,...,0.000,58.200,0.004,0.100,5.6,0.023,73.9,78.4,0.000,0.200
3,rice pudding,122,2.4,1.4,0.60,0.100,20.8,13.1,3.6,0.3,...,0.011,0.063,107.400,0.014,0.1,9.000,0.1,92.7,141.300,0.083
4,corn pudding,328,12.6,6.3,3.90,1.400,42.4,16.5,11.1,3.0,...,0.700,0.066,97.500,0.100,1.3,37.500,0.2,225.0,440.000,0.069

In [18]:
food_5 = pd.read_csv("../data/FOOD-DATA-GROUP5.csv")
food_5 = food_5.drop(["Unnamed: 0", "Unnamed: 0.1", "Nutrition Density"], axis=1)
food_5.head()

,food,Caloric Value,Fat,Saturated Fats,Monounsaturated Fats,Polyunsaturated Fats,Carbohydrates,Sugars,Protein,Dietary Fiber,...,Vitamin K,Calcium,Copper,Iron,Magnesium,Manganese,Phosphorus,Potassium,Selenium,Zinc
0,margarine with yoghurt,88,9.8,1.9,5.6,2.0,0.073,0.0,0.058,0.0,...,0.002,2.8,0.001,0.027,0.3,0.0,2.2,3.5,0.000,0.008
1,sunflower seed butter,99,8.8,0.7,6.2,1.6,3.700,1.7,2.800,0.9,...,0.000,10.2,0.300,0.700,49.8,0.3,106.6,92.2,0.075,0.800
2,hazelnut oil,120,13.6,1.0,10.6,1.4,0.000,0.0,0.000,0.0,...,0.000,0.0,0.000,0.000,0.0,0.0,0.0,0.0,0.000,0.000
3,menhaden fish oil,1966,218.0,66.3,58.2,74.5,0.000,0.0,0.000,0.0,...,0.000,0.0,0.000,0.000,0.0,0.0,0.0,0.0,0.000,0.000
4,cod liver fish oil,123,13.6,3.1,6.4,3.1,0.000,0.0,0.000,0.0,...,0.000,0.0,0.000,0.000,0.0,0.0,0.0,0.0,0.000,0.000

## Creando dataset a usar en chatbot

In [19]:
food_data = pd.concat(
    [food_1, food_2, food_3, food_3, food_4, food_5],
    ignore_index=True
)

In [20]:
print(food_data.shape)

(2966, 34)

In [21]:
food_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 2966 entries, 0 to 2965
Data columns (total 34 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   food                  2966 non-null   str
 1   Caloric Value         2966 non-null   int64
 2   Fat                   2966 non-null   float64
 3   Saturated Fats        2966 non-null   float64
 4   Monounsaturated Fats  2966 non-null   float64
 5   Polyunsaturated Fats  2966 non-null   float64
 6   Carbohydrates         2966 non-null   float64
 7   Sugars                2966 non-null   float64
 8   Protein               2966 non-null   float64
 9   Dietary Fiber         2966 non-null   float64
 10  Cholesterol           2966 non-null   float64
 11  Sodium                2966 non-null   float64
 12  Water                 2966 non-null   float64
 13  Vitamin A             2966 non-null   float64
 14  Vitamin B1            2966 non-null   float64
 15  Vitamin B11           2966 non-null   float64
 16  Vitamin B12           2966 non-null   float64
 17  Vitamin B2            2966 non-null   float64
 18  Vitamin B3            2966 non-null   float64
 19  Vitamin B5            2966 non-null   float64
 20  Vitamin B6            2966 non-null   float64
 21  Vitamin C             2966 non-null   float64
 22  Vitamin D             2966 non-null   float64
 23  Vitamin E             2966 non-null   float64
 24  Vitamin K             2966 non-null   float64
 25  Calcium               2966 non-null   float64
 26  Copper                2966 non-null   float64
 27  Iron                  2966 non-null   float64
 28  Magnesium             2966 non-null   float64
 29  Manganese             2966 non-null   float64
 30  Phosphorus            2966 non-null   float64
 31  Potassium             2966 non-null   float64
 32  Selenium              2966 non-null   float64
 33  Zinc                  2966 non-null   float64
dtypes: float64(32), int64(1), str(1)
memory usage: 788.0 KB

In [22]:
food_data.head()

,food,Caloric Value,Fat,Saturated Fats,Monounsaturated Fats,Polyunsaturated Fats,Carbohydrates,Sugars,Protein,Dietary Fiber,...,Vitamin K,Calcium,Copper,Iron,Magnesium,Manganese,Phosphorus,Potassium,Selenium,Zinc
0,cream cheese,51,5.0,2.9,1.3,0.200,0.8,0.500,0.9,0.0,...,0.100,0.008,14.100,0.082,0.027,1.300,0.091,15.5,19.100,0.039
1,neufchatel cheese,215,19.4,10.9,4.9,0.800,3.1,2.700,7.8,0.0,...,0.045,99.500,0.034,0.100,8.500,0.088,117.300,129.2,0.054,0.700
2,requeijao cremoso light catupiry,49,3.6,2.3,0.9,0.000,0.9,3.400,0.8,0.1,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.0,0.000,0.000
3,ricotta cheese,30,2.0,1.3,0.5,0.002,1.5,0.091,1.5,0.0,...,0.011,0.097,41.200,0.097,0.096,4.000,0.024,30.8,43.800,0.035
4,cream cheese low fat,30,2.3,1.4,0.6,0.042,1.2,0.900,1.2,0.0,...,0.019,22.200,0.072,0.008,1.200,0.098,22.800,37.1,0.034,0.053

In [23]:
print(food_data.duplicated().sum())

571

In [25]:
food_data = food_data.drop_duplicates()

In [26]:
print(food_data.duplicated().sum())

0

In [27]:
print(food_data.shape)

(2395, 34)